## A.4 The Backward Algorithm

In [1]:
from PRClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt

import numpy as np

In [12]:
# State generator
q = np.array( [ 1, 0 ] )
A = np.array( [ [ 0.9, 0.1, 0 ], [ 0, 0.9, 0.1 ] ] )
             
mc = MarkovChain(q, A) 

g1 = GaussD( means=[0], stdevs=[1] )   # Distribution for state = 1
g2 = GaussD( means=[3], stdevs=[2] )   # Distribution for state = 2
h  = HMM( mc, [g1, g2])                # The HMM

# Generate an output sequence
x = [-0.2, 2.6, 1.3]

# Generate px and scaler factors
px, scaler_px = h.Get_px(x)
np.set_printoptions(precision=4)
print("px is:")
print(px)
print()

# Print c
c = np.array([1, 0.1625, 0.8266, 0.0581])
print("c is:")
print(c)
print()

# The Backward Algorithm
betaHat = mc.backward(px, c)
print("betaHat is:")
print(betaHat)

px is:
[[1.     0.0695 1.    ]
 [0.1418 1.     0.8111]]

c is:
[1.     0.1625 0.8266 0.0581]

betaHat is:
[[1.0003 1.0393 0.    ]
 [8.4182 9.3536 2.0822]]
