In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
import numpy as np

In [4]:
# State generator
q = np.array([1, 0])
A = np.array([[0.9, 0.1, 0], [0, 0.9, 0.1]])
obsrv = np.array([-0.2, 2.6, 1.3])
mc = MarkovChain(initial_prob=q, transition_prob=A)

g1 = GaussD(means=[0], stdevs=[1])   # Distribution for state = 1
g2 = GaussD(means=[3], stdevs=[2])   # Distribution for state = 2
h = HMM(mc, [g1, g2])                # The HMM

pX, pX_scaled, factors = GaussD.prob(obsrv=obsrv, distr=[g1, g2])
alpha_hat, alpha_hat_scaled, c, c_scaled, prob_log, prob_log_scaled = HMM.logprob(obsrv, [g1, g2], mc)

print('pX:\n', pX)
print('alpha_hat:\n', alpha_hat)
print('c:', c)
print('prob_log:', prob_log, '\n')

print('pX_scaled:\n', pX_scaled)
print('alpha_hat_scaled:\n', alpha_hat_scaled)
print('c_scaled:', c_scaled)
print('prob_log_scaled:', prob_log_scaled)

pX:
 [[0.39104269 0.01358297 0.17136859]
 [0.05546042 0.19552135 0.13899244]]
alpha_hat:
 [[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
c: [0.39104269 0.03177681 0.14165001 0.05811253]
prob_log: -9.187726979475208 

pX_scaled:
 [[1.         0.06947052 1.        ]
 [0.14182701 1.         0.81107303]]
alpha_hat_scaled:
 [[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
c_scaled: [1.         0.16252347 0.82658096 0.05811253]
prob_log_scaled: -9.187726979475208
